version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    network_mode: "host"   # host mode for multicast to work
    restart: always

  client:
    build:
      context: .
      dockerfile: dockerfile.client
    network_mode: "host"
    restart: always
    scale: 3   # start 3 clients (can change number)
